name: vintpics
favicon: null
layout_spectrum: 0.7128754539880902
typography_spectrum: 0.46017739828675985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9685101399663836
  lightness: 0.6358661400154233
  saturation: 0.41762329428456724
  rhythmicContrast: 0.30732467002235353
purpose: []
